console.log("Hello World");
console.log(2 + 1);
console.log(typeof NaN);
console.log(400 + 0 / 0);
var i = 5;
if (i == 5) console.log("yeaaaaa!!");
// let input = prompt("Enter a Number");
// if (input == 5) console.log("qwertyuio");
// else console.log("qwertyuio");
let arr = [1, 2, 4, 6, 2, 5, 7, 3, 5, 1, 2, 8, 4, 1, 2, 6, 5];
arr.sort();
console.log(arr);
